remote_theme: qwtel/hydejack@v9
title: "Hadi Noori"
url: "https://hadinoori.ca"

# This activates the professional sidebar
hydejack:
  show_author: true
  show_sidebar: true
  sidebar_menu:
    - title: "Home"
      url: "/"
    - title: "About"
      url: "/about/"
    - title: "Resume"
      url: "/resume/"

# Required Plugins
plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
