remote_theme: qwtel/hydejack@v9
title: "Hadi Noori"

# Menu Configuration
hydejack:
  sidebar_menu:
    - title: "Home"
      url: "/"
    - title: "Projects"
      url: "/projects/"
    - title: "Publications"
      url: "/publications/"
    - title: "Blog"
      url: "/blog/"
    - title: "About"
      url: "/about/"

# Content Organization
permalink: /:title/
paginate: 5
paginate_path: "/blog/page:num/"
